paths:
  reviews_dir: pilot_inputs/reviews
  pdf_dir: pilot_inputs/sources_pdf
  sources_pdf_dir: pilot_inputs/sources_pdf
  sources_text_dir: working/sources_text
  indices_dir: working/indices
  outputs_dir: outputs

llm:
  provider: openai
  model: gpt-4o
  temperature: 0.0
  max_output_tokens: 800

retrieval:
  chunk_words: 180
  chunk_stride: 90
  top_k: 5

adjudication:
  max_candidates_per_source: 3
  json_schema_path: prompts/adjudicator_json_schema.json

runtime:
  concurrency: 3